CREATE TABLE TB_PASSENGER_4 (
  DRIVERID INTEGER,
  VENDORID INTEGER,
  TPEP_PICKUP_DATETIME VARCHAR(30),
  TPEP_DROPOFF_DATETIME VARCHAR(30),
  PASSENGER_COUNT INTEGER,
  TRIP_DISTANCE FLOAT,
  PICKUP_LONGITUDE FLOAT,
  PICKUP_LATITUDE FLOAT,
  RATECODEID INTEGER,
  STORE_AND_FWD_FLAG VARCHAR(5),
  DROPOFF_LONGITUDE FLOAT,
  DROPOFF_LATITUDE FLOAT,
  PAYMENT_TYPE INTEGER,
  FARE_AMOUNT FLOAT,
  EXTRA FLOAT,
  MTA_TAX FLOAT,
  TIP_AMOUNT FLOAT,
  TOLLS_AMOUNT FLOAT,
  IMPROVEMENT_SURCHARGE FLOAT,
  TOTAL_AMOUNT FLOAT
);
GO

CREATE INDEX IDX_TB_PASSENGER4_DRIVERID ON TB_PASSENGER_4 (DRIVERID);
GO

CREATE TABLE TB_PASSENGER (
  DRIVERID INTEGER,
  VENDORID INTEGER,
  TPEP_PICKUP_DATETIME VARCHAR(30),
  TPEP_DROPOFF_DATETIME VARCHAR(30),
  PASSENGER_COUNT INTEGER,
  TRIP_DISTANCE FLOAT,
  PICKUP_LONGITUDE FLOAT,
  PICKUP_LATITUDE FLOAT,
  RATECODEID INTEGER,
  STORE_AND_FWD_FLAG VARCHAR(5),
  DROPOFF_LONGITUDE FLOAT,
  DROPOFF_LATITUDE FLOAT,
  PAYMENT_TYPE INTEGER,
  FARE_AMOUNT FLOAT,
  EXTRA FLOAT,
  MTA_TAX FLOAT,
  TIP_AMOUNT FLOAT,
  TOLLS_AMOUNT FLOAT,
  IMPROVEMENT_SURCHARGE FLOAT,
  TOTAL_AMOUNT FLOAT
);
GO

CREATE INDEX IDX_TB_PASSENGER_DRIVERID ON TB_PASSENGER (DRIVERID);
GO

CREATE TABLE TB_AMOUNT_40 (
  DRIVERID INTEGER,
  VENDORID INTEGER,
  TPEP_PICKUP_DATETIME VARCHAR(30),
  TPEP_DROPOFF_DATETIME VARCHAR(30),
  PASSENGER_COUNT INTEGER,
  TRIP_DISTANCE FLOAT,
  PICKUP_LONGITUDE FLOAT,
  PICKUP_LATITUDE FLOAT,
  RATECODEID INTEGER,
  STORE_AND_FWD_FLAG VARCHAR(5),
  DROPOFF_LONGITUDE FLOAT,
  DROPOFF_LATITUDE FLOAT,
  PAYMENT_TYPE INTEGER,
  FARE_AMOUNT FLOAT,
  EXTRA FLOAT,
  MTA_TAX FLOAT,
  TIP_AMOUNT FLOAT,
  TOLLS_AMOUNT FLOAT,
  IMPROVEMENT_SURCHARGE FLOAT,
  TOTAL_AMOUNT FLOAT
);
GO

CREATE INDEX IDX_TB_AMOUNT40_DRIVERID ON TB_AMOUNT_40 (DRIVERID);
GO

CREATE TABLE TB_AMOUNT (
  DRIVERID INTEGER,
  VENDORID INTEGER,
  TPEP_PICKUP_DATETIME VARCHAR(30),
  TPEP_DROPOFF_DATETIME VARCHAR(30),
  PASSENGER_COUNT INTEGER,
  TRIP_DISTANCE FLOAT,
  PICKUP_LONGITUDE FLOAT,
  PICKUP_LATITUDE FLOAT,
  RATECODEID INTEGER,
  STORE_AND_FWD_FLAG VARCHAR(5),
  DROPOFF_LONGITUDE FLOAT,
  DROPOFF_LATITUDE FLOAT,
  PAYMENT_TYPE INTEGER,
  FARE_AMOUNT FLOAT,
  EXTRA FLOAT,
  MTA_TAX FLOAT,
  TIP_AMOUNT FLOAT,
  TOLLS_AMOUNT FLOAT,
  IMPROVEMENT_SURCHARGE FLOAT,
  TOTAL_AMOUNT FLOAT
);
GO

CREATE INDEX IDX_TB_AMOUNT_DRIVERID ON TB_AMOUNT (DRIVERID);
GO

CREATE TABLE TB_TIME_PM (
  DRIVERID INTEGER,
  VENDORID INTEGER,
  TPEP_PICKUP_DATETIME VARCHAR(30),
  TPEP_DROPOFF_DATETIME VARCHAR(30),
  PASSENGER_COUNT INTEGER,
  TRIP_DISTANCE FLOAT,
  PICKUP_LONGITUDE FLOAT,
  PICKUP_LATITUDE FLOAT,
  RATECODEID INTEGER,
  STORE_AND_FWD_FLAG VARCHAR(5),
  DROPOFF_LONGITUDE FLOAT,
  DROPOFF_LATITUDE FLOAT,
  PAYMENT_TYPE INTEGER,
  FARE_AMOUNT FLOAT,
  EXTRA FLOAT,
  MTA_TAX FLOAT,
  TIP_AMOUNT FLOAT,
  TOLLS_AMOUNT FLOAT,
  IMPROVEMENT_SURCHARGE FLOAT,
  TOTAL_AMOUNT FLOAT
);
GO

CREATE INDEX IDX_TB_TIME_PM ON TB_AMOUNT (DRIVERID);
GO

CREATE TABLE TB_TIME_AM (
  DRIVERID INTEGER,
  VENDORID INTEGER,
  TPEP_PICKUP_DATETIME VARCHAR(30),
  TPEP_DROPOFF_DATETIME VARCHAR(30),
  PASSENGER_COUNT INTEGER,
  TRIP_DISTANCE FLOAT,
  PICKUP_LONGITUDE FLOAT,
  PICKUP_LATITUDE FLOAT,
  RATECODEID INTEGER,
  STORE_AND_FWD_FLAG VARCHAR(5),
  DROPOFF_LONGITUDE FLOAT,
  DROPOFF_LATITUDE FLOAT,
  PAYMENT_TYPE INTEGER,
  FARE_AMOUNT FLOAT,
  EXTRA FLOAT,
  MTA_TAX FLOAT,
  TIP_AMOUNT FLOAT,
  TOLLS_AMOUNT FLOAT,
  IMPROVEMENT_SURCHARGE FLOAT,
  TOTAL_AMOUNT FLOAT
);
GO

CREATE INDEX IDX_TB_TIME_AM ON TB_AMOUNT (DRIVERID);
GO

CREATE INDEX IDX_TB_TIME_PM ON TB_AMOUNT (DRIVERID);
GO

CREATE TABLE TB_DRIVER (
  DRIVERID INTEGER,
  VENDORID INTEGER,
  TPEP_PICKUP_DATETIME VARCHAR(30),
  TPEP_DROPOFF_DATETIME VARCHAR(30),
  PASSENGER_COUNT INTEGER,
  TRIP_DISTANCE FLOAT,
  PICKUP_LONGITUDE FLOAT,
  PICKUP_LATITUDE FLOAT,
  RATECODEID INTEGER,
  STORE_AND_FWD_FLAG VARCHAR(5),
  DROPOFF_LONGITUDE FLOAT,
  DROPOFF_LATITUDE FLOAT,
  PAYMENT_TYPE INTEGER,
  FARE_AMOUNT FLOAT,
  EXTRA FLOAT,
  MTA_TAX FLOAT,
  TIP_AMOUNT FLOAT,
  TOLLS_AMOUNT FLOAT,
  IMPROVEMENT_SURCHARGE FLOAT,
  TOTAL_AMOUNT FLOAT
);
GO

CREATE INDEX IDX_TB_DRIVER ON TB_DRIVER (DRIVERID);
GO
